### ISSUE TITLE
Error in command 'atransfer deposit'. Insufficient funds

### ISSUE THREAD

**Issue by sirenondine** [aikaterna/gobcog#271]
`Exception in command 'atransfer deposit'
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/admin/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 7090, in commands_atransfer_deposit
    await bank.withdraw_credits(member=ctx.author, amount=amount, _forced=True)
  File "/home/admin/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/bank.py", line 252, in withdraw_credits
    return await bank.withdraw_credits(member=member, amount=amount)
  File "/home/admin/.local/lib/python3.8/site-packages/redbot/core/bank.py", line 269, in withdraw_credits
    raise ValueError(
ValueError: Insufficient funds 2,000 > 1,000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/admin/.local/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/admin/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/admin/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/admin/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Insufficient funds 2,000 > 1,000`

Sorry I should have checked for this with #269  :crying_cat_face:

**Comment by Drapersniper** [comment]
Not at all this is due my stupidity ... and only checking the code once...
