### ISSUE TITLE
[Bug] Running does not actually decreases money

### ISSUE THREAD

**Issue by fixator10** [aikaterna/gobcog#321]
- [X] I confirm that I am the owner of the bot running Adventure.
- [X] I confirm that I have not modified the source code of Adventure.
- [X] I'm an Adventure user but not the bot owner. (State, in which bug occurred)
- [X] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
Running withdraws money

## Current Behavior
Bot says that money is used, but it is still in bank

## Steps to Reproduce
1. Check your balance
2. Wait until someone else start an adventure
3. Run from it
4. Wait for adventure to end
5. Check your balance again

![img](https://moeka.is-a-good-waifu.com/X8NYDPn.png)
![img](https://moeka.is-a-good-waifu.com/7KYcA5N.png)
![img](https://moeka.is-a-good-waifu.com/9yymiJW.png)

**Comment by fixator10** [comment]
There is also random tracebacks thats by timestamp doesnt seems to be related, by still can be related.
```py
Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 7282, in on_message_without_command
    await self._trader(ctx)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 7792, in _trader
    msg = await room.send(text)
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/discord/abc.py", line 890, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions```

```py
[2020-09-18 11:01:01] [ERROR] red: ValueError
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 1726, in backpack_trade
    await bank.transfer_credits(buyer, ctx.author, asking)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/bank.py", line 325, in transfer_credits
    return await bank.transfer_credits(from_=from_, to=to, amount=amount)
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/core/bank.py", line 428, in transfer_credits
    raise ValueError(
ValueError: Invalid transfer amount -5 <= 0
[2020-09-18 11:02:07] [ERROR] red: ValueError
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 1726, in backpack_trade
    await bank.transfer_credits(buyer, ctx.author, asking)
  File "/home/fixator/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/bank.py", line 325, in transfer_credits
    return await bank.transfer_credits(from_=from_, to=to, amount=amount)
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/core/bank.py", line 428, in transfer_credits
    raise ValueError(
ValueError: Invalid transfer amount -5 <= 0```
