### ISSUE TITLE
[Bug] User lost all set items after negaverse (3.4.1)

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#336]
## Complete these first
- [x] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
User rebirthed, didn't get anything and on top of that lost all their set item

## Current Behavior
Adventure version: 3.4.1

## Steps to Reproduce

Picture 1, user Negaversed (bot time is -3 hrs): 
![bug-adv1](https://user-images.githubusercontent.com/31835797/98444381-6a3e3b00-2122-11eb-8eb1-ba4c2cef0b66.png)
Picture 2, their stats screen right after that 
![bug-adv2](https://user-images.githubusercontent.com/31835797/98444407-8cd05400-2122-11eb-944e-c7c06002c928.png)
Picture 3, their set items before the bug
![bug-adv4](https://user-images.githubusercontent.com/31835797/98444414-9eb1f700-2122-11eb-9368-1d1d44392647.png)
And lastly, their set items now
![bug-adv3](https://user-images.githubusercontent.com/31835797/98444420-a4a7d800-2122-11eb-8c97-d2cf3022f13f.png)
## Detailed Description
Traceback/log of the time it happening (5 oclock time, 8 oclock approx on screenshot)

```
[2020-11-07 05:38:03] [ERROR] red: RuntimeError
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 3899, in loot
    await self._open_chest(ctx, ctx.author, box_type, character=c)  # returns item and msg
  File "/usr/lib/python3.8/asyncio/locks.py", line 103, in __aexit__
    self.release()
  File "/usr/lib/python3.8/asyncio/locks.py", line 229, in release
    raise RuntimeError('Lock is not acquired.')
RuntimeError: Lock is not acquired.
[2020-11-07 05:54:37] [INFO] red.cleanup: vitalxx(209158311885406218) deleted 2 messages sent by the bot in channel gid-adventures.
[2020-11-07 13:58:59] [ERROR] red.cogs.adventure: Error with the countdown timer
Traceback (most recent call last):
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 5754, in _choice
    await asyncio.wait_for(timer, timeout=timeout + 5)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 7150, in adv_countdown
    await message_adv.edit(content=f"â³ [{title}] {timer}s")
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/message.py", line 843, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: overflow
[2020-11-07 13:59:03] [ERROR] red.cogs.adventure: Something went wrong controlling the game
Traceback (most recent call last):
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 5328, in _adventure
    reward, participants = await self._simple(ctx, adventure_msg, challenge)
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 5613, in _simple
    await self._choice(ctx, adventure_msg)
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 5759, in _choice
    return await self._result(ctx, adventure_msg)
  File "/home/ubuntu/red/cogs/CogManager/cogs/adventure/adventure.py", line 6127, in _result
    await calc_msg.delete()
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/message.py", line 760, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: overflow
```

## Possible Implementation
User has been "refunded" with 27 set chests as a solution. Didn't happen before so I hope it's not happening again.

**Comment by aikaterna** [comment]
Considering you are on an old version I don't have any help for you on this. Normally I would close this but I am going to leave it open for another month or two to see if anyone else on the current version has the same issue.

**Comment by Drapersniper** [comment]
Close this now?
