### ISSUE TITLE
Reaction Lag? [adv]

### ISSUE THREAD

**Issue by kalaiath** [aikaterna/gobcog#343]
Sometimes adventure doesn’t recognize reactions even though the timer is anywhere from 30 second to 3 minutes remaining.

**Comment by aikaterna** [comment]
Possibly related to
```
[2021-01-08 18:13:37] [ERROR] red.cogs.adventure: Error with the countdown timer
Traceback (most recent call last):
  File "/.../Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 5810, in _choice
    await asyncio.wait_for(timer, timeout=timeout + 5)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
