### ISSUE TITLE
[Bug] Division by zero

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#421]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure. :trollface: 
- [ ] I'm an Adventure user but not the bot owner.
- [ ] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

```
Traceback (most recent call last):
  File "/root/MELON/lib/python3.9/site-packages/discord/ext/commands/core.py", line 86, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/MELON/cogs/CogManager/cogs/adventure/rebirth.py", line 53, in rebirth
    ) or (c.static_last_known_currency is not None and (current_balance / c.static_last_known_currency) < 0.5):
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MELON/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/root/MELON/lib/python3.9/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/MELON/lib/python3.9/site-packages/discord/ext/commands/core.py", line 95, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ZeroDivisionError: division by zero
```
https://discord.com/channels/133049272517001216/171665724262055936/1101419501293150270

**Comment by jackpoz** [comment]
Do you have custom changes ? `static_last_known_currency` is nowhere to be found in the source code.
Could you post your `/root/.local/share/Red-DiscordBot/data/MELON/cogs/CogManager/cogs/adventure/rebirth.py` file ?

**Comment by aikaterna** [comment]
They did probably have custom changes. No need for me to open an issue for them then.
