### ISSUE TITLE
`[p]forge` throws errors when trying to choose item

### ISSUE THREAD

**Issue by jack1142** [aikaterna/gobcog#49]
Traceback:
```
Exception in command 'forge'
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red-data/cogs/CogManager/cogs/adventure/adventure.py", line 1228, in forge
    if item.rarity == "forgeable":
AttributeError: 'NoneType' object has no attribute 'rarity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'rarity'
```

**Comment by Skyrid3r** [comment]
Can confirm this issue. Tinkerer appears to be a broken hero atm. Regardless what item name you choose through DM, partial or full item name. The bot will throw out that error above.

```Traceback (most recent call last):
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/skyrider/discord/redv3/cogs/CogManager/cogs/adventure/adventure.py", line 1228, in forge
    if item.rarity == "forgeable":
AttributeError: 'NoneType' object has no attribute 'rarity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/skyrider/.virtualenvs/redv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'rarity'```

**Comment by 404DeveloperNotFound** [comment]
Can Confirm this as well
`Traceback (most recent call last):
  File "/home/vault108/Sally/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/vault108/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 1228, in forge
    if item.rarity == "forgeable":
AttributeError: 'NoneType' object has no attribute 'rarity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vault108/Sally/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/vault108/Sally/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/vault108/Sally/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'rarity'`
