### ISSUE TITLE
trying to use backpack sell, or backpack sell all fails in DMs

### ISSUE THREAD

**Issue by kennnyshiwa** [aikaterna/gobcog#61]
When using backpack sell and or sellall in dms the command errors out with the following traceback 

```Exception in command 'backpack sell'
Traceback (most recent call last):
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kstjohn_kstj_us/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 478, in backpack_sell
    await bank.deposit_credits(ctx.author, price)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/redbot/core/bank.py", line 303, in deposit_credits
    return await set_balance(member, amount + bal)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/redbot/core/bank.py", line 199, in set_balance
    max_bal = await get_max_balance(member.guild)
AttributeError: 'User' object has no attribute 'guild'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 570, in invoke
    await super().invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1158, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kstjohn_kstj_us/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'User' object has no attribute 'guild'````

**Comment by 404DeveloperNotFound** [comment]
It also states "this command is not available in DM's on this bot" I may be wrong but the reason it errors is because the dm has no guild id. Now if you run it in a server it will have a guild id. And you should be able to sell what you have in the back pack for that server.
